//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1434.
// 
#pragma warning disable 1591

namespace SMSAlertReader.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://labs.innovativesingapore.com/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkvalidityOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSubscribedMessagesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::SMSAlertReader.Properties.Settings.Default.SMSAlertReader_WebReference_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        public event checkvalidityCompletedEventHandler checkvalidityCompleted;
        
        /// <remarks/>
        public event getSubscribedMessagesCompletedEventHandler getSubscribedMessagesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://labs.innovativesingapore.com/SendSMS", RequestNamespace="http://labs.innovativesingapore.com/", ResponseNamespace="http://labs.innovativesingapore.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS(string message, string destinationNumber, string username, string password) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        message,
                        destinationNumber,
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(string message, string destinationNumber, string username, string password) {
            this.SendSMSAsync(message, destinationNumber, username, password, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(string message, string destinationNumber, string username, string password, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        message,
                        destinationNumber,
                        username,
                        password}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://labs.innovativesingapore.com/checkvalidity", RequestNamespace="http://labs.innovativesingapore.com/", ResponseNamespace="http://labs.innovativesingapore.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkvalidity(string message, string destinationNumber, string username, string password) {
            object[] results = this.Invoke("checkvalidity", new object[] {
                        message,
                        destinationNumber,
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkvalidityAsync(string message, string destinationNumber, string username, string password) {
            this.checkvalidityAsync(message, destinationNumber, username, password, null);
        }
        
        /// <remarks/>
        public void checkvalidityAsync(string message, string destinationNumber, string username, string password, object userState) {
            if ((this.checkvalidityOperationCompleted == null)) {
                this.checkvalidityOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckvalidityOperationCompleted);
            }
            this.InvokeAsync("checkvalidity", new object[] {
                        message,
                        destinationNumber,
                        username,
                        password}, this.checkvalidityOperationCompleted, userState);
        }
        
        private void OncheckvalidityOperationCompleted(object arg) {
            if ((this.checkvalidityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkvalidityCompleted(this, new checkvalidityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://labs.innovativesingapore.com/getSubscribedMessages", RequestNamespace="http://labs.innovativesingapore.com/", ResponseNamespace="http://labs.innovativesingapore.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getSubscribedMessages(string username, string password, int applicationID) {
            object[] results = this.Invoke("getSubscribedMessages", new object[] {
                        username,
                        password,
                        applicationID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getSubscribedMessagesAsync(string username, string password, int applicationID) {
            this.getSubscribedMessagesAsync(username, password, applicationID, null);
        }
        
        /// <remarks/>
        public void getSubscribedMessagesAsync(string username, string password, int applicationID, object userState) {
            if ((this.getSubscribedMessagesOperationCompleted == null)) {
                this.getSubscribedMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSubscribedMessagesOperationCompleted);
            }
            this.InvokeAsync("getSubscribedMessages", new object[] {
                        username,
                        password,
                        applicationID}, this.getSubscribedMessagesOperationCompleted, userState);
        }
        
        private void OngetSubscribedMessagesOperationCompleted(object arg) {
            if ((this.getSubscribedMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSubscribedMessagesCompleted(this, new getSubscribedMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void checkvalidityCompletedEventHandler(object sender, checkvalidityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkvalidityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkvalidityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    public delegate void getSubscribedMessagesCompletedEventHandler(object sender, getSubscribedMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1434")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSubscribedMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSubscribedMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591